### PR TITLE
add logout on function to allEvents.goToHome()

### PR DESCRIPTION
**Pull request by RussellRiesJr**

### CODE REVIEW

**Comment by MeganWord** [comment]
is there a way to make this function available on all the pages? like maybe we need to nest our controllers in a 'master' controller so that this logout function is available to our users from any page? I did this in my capstone and it wasn't too hard.

**Comment by AlanE23** [comment]
🐫

**Comment by AlanE23** [comment]
🍰

**Comment by chase-ramsey** [comment]
🍂

**Pull request merged**
